spring:
  application:
    name: user-center
  profiles:
    active: prod
  hikari:
    connection-timeout: 30000  # 数据库连接超时时间，单位是毫秒，这里设置为30秒
    validation-timeout: 5000   # 测试连接超时时间，单位也是毫秒，可选配置
    idle-timeout: 600000       # 连接空闲超时时间，单位是毫秒，这里设置为10分钟
    max-lifetime: 1800000     # 连接最大生命周期，单位是毫秒，这里设置为30分钟
    maximum-pool-size: 10     # 连接池最大连接数
server:
  servlet:
    context-path: /api


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
